// src/frameworks/react/resources/App.jsx
import { useState } from 'react'
import reactLogo from '@/react.svg'

function App() {
	const [count, setCount] = useState(0)
  	return (
    	<div className="App">
			<div className="logos">
				<img src="https://github.com/firtadokei/codeigniter-vitejs/raw/master/src/logo.png" className="logo" alt="Codeigniter vite logo" />
				<img src={reactLogo} className="logo" alt="React logo" />
			</div>
			<h2>Codeigniter Vite + React</h2>
			<p>
				<button onClick={() => setCount((count) => count + 1)}>
					count is {count}
				</button>
			</p>
      		<p>Edit resources/App.jsx and save to test HMR</p>
    	</div>
  	)
}

export default App

// src/Config/svelte/resources/App.svelte
<script>
import svelteLogo from "@/svelte.svg";

let count = 0;
const increment =
	() => {
		count += 1;
	};
</script>

<main>
	<div
		class="container">
		<div
			class="logos">
			<img
				src="https://github.com/firtadokei/codeigniter-vitejs/raw/master/src/logo.png"
				class="logo"
				alt="Codeigniter vite logo" />
			<img
				src={svelteLogo}
				class="logo"
				alt="Svelte logo" />
		</div>
		<h2>
			Codeigniter
			Vite
			+
			Svelte
		</h2>
		<p>
			<button
				on:click={increment}
				>Count
				is
				{count}</button>
		</p>
		<p>
			Edit
			resources/App.svelte
			to
			test
			HMR
		</p>
	</div>
</main>

<style>
</style>
